version: '3.1'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_python_jupyter
    command: jupyter lab --ip=0.0.0.0 --allow-root
    volumes:
      - ./:/jupyter
    working_dir: /jupyter
    ports:
      - 8888:8888
